FROM python:3.9-slim

WORKDIR /app

# Install additional system dependencies
RUN apt-get update && apt-get install -y \
    dnsutils \
    && rm -rf /var/lib/apt/lists/*

ENV PATH="$PATH:/root/go/bin:/root/.pdtm/go/bin:/usr/lib/go-1.15/bin"

RUN apt-get update && apt-get install -y \
    git \
    golang-go \
    jq \
    prips \
    nmap \
    unzip \
    wget \
    && rm -rf /var/lib/apt/lists/*

COPY h3xrecon-server /app/h3xrecon-server

COPY h3xrecon-core /app/h3xrecon-core

RUN python3 -m venv /app/venv && \
    /app/venv/bin/pip install /app/h3xrecon-server && \
    /app/venv/bin/pip install /app/h3xrecon-core

COPY entrypoint.sh /entrypoint.sh

RUN chmod +x /entrypoint.sh

ENV PYTHONUNBUFFERED=1

ENV PYTHONFAULTHANDLER=1

CMD ["/entrypoint.sh"]