- name: Start h3xrecon stack
  hosts: processor
  vars_files:
    - vaults/vault.yaml
  tasks:
    - name: Create target directory
      ansible.builtin.file:
        path: "{{ h3xrecon_target_directory }}"
        state: directory

    - name: Copy compose files
      ansible.builtin.copy:
        src: "{{ file['src'] }}"
        dest: "{{ file['dest'] }}"
      loop:
        - src: ../../docker/grafana
          dest: "{{ h3xrecon_target_directory }}"
        - src: ../docker-compose.swarm.yaml
          dest: "{{ h3xrecon_target_directory }}/docker-compose.yaml"
        - src: ../../.env.compose
          dest: "{{ h3xrecon_target_directory }}.env"
        - src: ../../docker/msgbroker
          dest: "{{ h3xrecon_target_directory }}"
      loop_control:
        loop_var: file

    - name: Deploy Docker stack
      ansible.builtin.shell:
        chdir: "{{ h3xrecon_target_directory }}"
        cmd: |
          export $(cat .env) > /dev/null 2>&1; docker stack deploy -c docker-compose.yaml h3xrecon
      register: docker_stack_deploy
    - name: Display Docker stack deploy result
      ansible.builtin.debug:
        var: docker_stack_deploy
