services:
  cache:
    image: redis:6.2-alpine
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --protected-mode no
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    ports:
      - target: 6379
        published: 6379
    deploy:
      placement:
        constraints:
          - node.labels.h3xrecon_role == processor
  
  database:
    environment:
      - POSTGRES_PASSWORD=${H3XRECON_DB_PASS}
      - POSTGRES_USER=h3xrecon
      - POSTGRES_DB=h3xrecon
    image: ghcr.io/h3xitsec/h3xrecon_pgsql:latest
    volumes:
      - pgsql_data:/var/lib/postgresql/data
    ports:
      - target: 5432
        published: 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U h3xrecon -d h3xrecon"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.h3xrecon_role == processor

  msgbroker:
    image: ghcr.io/h3xitsec/h3xrecon_msgbroker:latest
    volumes:
      - nats_data:/data
    ports:
      - target: 4222
        published: 4222
    healthcheck:
      test: nats stream ls --server=nats://localhost:4222 | grep -q "FUNCTION_EXECUTE" && nats stream ls --server=nats://localhost:4222 | grep -q "FUNCTION_OUTPUT" && nats stream ls --server=nats://localhost:4222 | grep -q "RECON_DATA"
      interval: 2s
      timeout: 2s
      retries: 5
      start_period: 5s
    deploy:
      placement:
        constraints:
          - node.labels.h3xrecon_role == processor
  
  logging:
    env_file: .env.compose
    image: ghcr.io/h3xitsec/h3xrecon:latest
    depends_on:
      - msgbroker:service_healthy
      - database:service_healthy
    environment:
      - H3XRECON_ROLE=logging
    deploy:
      placement:
        constraints:
          - node.labels.h3xrecon_role == processor
  
  jobprocessor:
    env_file: .env.compose
    image: ghcr.io/h3xitsec/h3xrecon:latest
    depends_on:
      - msgbroker:service_healthy
      - cache:service_healthy
    environment:
      - H3XRECON_ROLE=jobprocessor
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.h3xrecon_role == processor
  
  dataprocessor:
    env_file: .env.compose
    image: ghcr.io/h3xitsec/h3xrecon:latest
    depends_on:
      - msgbroker:service_healthy
      - cache:service_healthy
    environment:
      - H3XRECON_ROLE=dataprocessor
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.h3xrecon_role == processor
  
  worker:
    env_file: .env.compose
    image: ghcr.io/h3xitsec/h3xrecon:latest
    depends_on:
      - msgbroker:service_healthy
      - cache:service_healthy
    environment:
      - H3XRECON_ROLE=worker
    deploy:
      mode: replicated
      replicas: 5
      placement:
        constraints:
          - node.labels.h3xrecon_role == worker

volumes:
  pgsql_data: {}
  redis_data: {}
  nats_data: {}
  tailscale_state: {}