services:
  cache:
    image: redis:6.2-alpine
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --protected-mode no
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    ports:
      - "6379:6379"  # Updated for local mode

  database:
    image: ghcr.io/h3xitsec/h3xrecon_pgsql:latest
    env_file: .env.compose
    environment:
      - POSTGRES_PASSWORD=${H3XRECON_DB_PASS}
      - POSTGRES_USER=${H3XRECON_DB_USER}
      - POSTGRES_DB=${H3XRECON_DB_NAME}
    volumes:
      - pgsql_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # Updated for local mode
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${H3XRECON_DB_USER} -d ${H3XRECON_DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  msgbroker:
    image: ghcr.io/h3xitsec/h3xrecon_msgbroker:latest
    env_file: .env.compose
    volumes:
      - nats_data:/data
    ports:
      - "4222:4222"  # Updated for local mode
    healthcheck:
      test: ["CMD-SHELL", "nats stream ls --server=nats://localhost:4222 | grep -q 'FUNCTION_EXECUTE' && nats stream ls --server=nats://localhost:4222 | grep -q 'FUNCTION_OUTPUT' && nats stream ls --server=nats://localhost:4222 | grep -q 'RECON_DATA'"]
      interval: 2s
      timeout: 2s
      retries: 5
      start_period: 5s

  logging:
    image: ghcr.io/h3xitsec/h3xrecon:latest
    env_file: .env.compose
    environment:
      - H3XRECON_ROLE=logging
    depends_on:
      database:
        condition: service_healthy
      msgbroker:
        condition: service_healthy

  jobprocessor:
    image: ghcr.io/h3xitsec/h3xrecon:latest
    env_file: .env.compose
    environment:
      - H3XRECON_ROLE=jobprocessor
    depends_on:
      msgbroker:
        condition: service_healthy
      cache:
        condition: service_healthy

  dataprocessor:
    image: ghcr.io/h3xitsec/h3xrecon:latest
    env_file: .env.compose
    environment:
      - H3XRECON_ROLE=dataprocessor
    depends_on:
      msgbroker:
        condition: service_healthy
      cache:
        condition: service_healthy

  worker:
    image: ghcr.io/h3xitsec/h3xrecon:latest
    env_file: .env.compose
    environment:
      - H3XRECON_ROLE=worker
    depends_on:
      msgbroker:
        condition: service_healthy

volumes:
  pgsql_data:
  redis_data:
  nats_data:
