{
 "title": "h3xrecon_data",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "_program_name", "label": "Program Name", "query": "select name from programs;" }
  ]
 },
 "panels": [
  {
   "title": "Domains",
   "type": "table",
   "gridPos": { "h": 14, "w": 13, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT d.domain, d.discovered_at, i.ip  \nFROM domains d \nJOIN programs p ON p.id = d.program_id \nLEFT JOIN ips i ON i.id = ANY(d.ips) \nWHERE p.name = '$_program_name' \nORDER BY i.ip NULLS LAST"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(d.id) FROM domains d JOIN programs p ON p.id = d.program_id WHERE p.name = '$_program_name'"
    }
   ]
  },
  {
   "title": "10 last discovered domains",
   "type": "table",
   "gridPos": { "h": 12, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT d.domain, d.discovered_at\nFROM domains d \nJOIN programs p ON p.id = d.program_id \nWHERE p.name = '$_program_name' \nORDER BY d.discovered_at DESC\nLIMIT 10"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 13, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(u.id) FROM urls u JOIN programs p ON p.id = u.program_id WHERE p.name = '$_program_name'"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 13, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(c.id) FROM certificates c JOIN programs p ON p.id = c.program_id WHERE p.name = '$_program_name'"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 13, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(n.id) FROM nuclei n JOIN programs p ON p.id = n.program_id WHERE p.name = '$_program_name'"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 13, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(i.id) FROM ips i JOIN programs p ON p.id = i.program_id WHERE p.name = '$_program_name'"
    }
   ]
  },
  {
   "title": "10 last discovered URLs",
   "type": "table",
   "gridPos": { "h": 12, "w": 9, "x": 15, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT u.url, u.discovered_at\nFROM urls u \nJOIN programs p ON p.id = u.program_id \nWHERE p.name = '$_program_name' \nORDER BY u.discovered_at DESC\nLIMIT 10"
    }
   ]
  },
  {
   "title": "URLs",
   "type": "table",
   "gridPos": { "h": 14, "w": 13, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT u.url, u.title, u.status_code,u.content_type FROM urls u JOIN programs p ON p.id = u.program_id WHERE p.name = '$_program_name'SELECT u.url, u.title, u.status_code, c.serial as certificate FROM urls u JOIN programs p ON p.id = u.program_id LEFT JOIN certificates c ON u.id = ANY(c.url_id) WHERE p.name = '$_program_name'"
    }
   ]
  },
  {
   "title": "10 last discovered certificates",
   "type": "table",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT c.subject_cn, c.discovered_at\nFROM certificates c\nJOIN programs p ON p.id = c.program_id \nWHERE p.name = '$_program_name' \nORDER BY c.discovered_at DESC\nLIMIT 10"
    }
   ]
  },
  {
   "title": "Certificates",
   "type": "table",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 28 },
   "targets": [
    {
     "rawSql": "SELECT c.subject_cn, c.issuer_org, c.serial, c.valid_date, c.expiry_date, array_length(c.subject_an, 1) as subject_an_count FROM certificates c JOIN programs p ON p.id = c.program_id WHERE p.name = '$_program_name'SELECT c.subject_cn, c.issuer_org, c.serial, c.valid_date, c.expiry_date, array_length(c.subject_an, 1) as subject_an_count, array_length(c.url_id, 1) as url_count FROM certificates c JOIN programs p ON p.id = c.program_id WHERE p.name = '$_program_name'"
    }
   ]
  },
  {
   "title": "Nuclei",
   "type": "table",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 38 },
   "targets": [
    {
     "rawSql": "SELECT n.url, n.template_id, n.severity, n.matcher_name\nFROM nuclei n\nJOIN programs p ON p.id = n.program_id \nWHERE p.name = '$_program_name'"
    }
   ]
  },
  {
   "title": "IPs",
   "type": "table",
   "gridPos": { "h": 12, "w": 13, "x": 0, "y": 48 },
   "targets": [
    {
     "rawSql": "SELECT i.ip, i.ptr\nFROM ips i\nJOIN programs p ON p.id = i.program_id \nWHERE p.name = '$_program_name' \nORDER BY i.ptr NULLS LAST"
    }
   ]
  }
 ]
}