{
 "title": "Components Output",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Recon Worker Logs",
   "type": "logs",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{service_name=~\".*h3xrecon_recon.*\"} !~ `^$`"
    }
   ]
  },
  {
   "title": "Parsing Worker Logs",
   "type": "logs",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{service_name=~\".*h3xrecon_parsing.*\"} !~ `^$`"
    }
   ]
  },
  {
   "title": "Data Worker Logs",
   "type": "logs",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "{service_name=~\".*h3xrecon_data.*\"} !~ `^$`"
    }
   ]
  }
 ]
}