{
 "title": "Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "_recon_filter", "label": "Recon Filter" },
   { "name": "_parsing_filter", "label": "Parsing Filter" },
   { "name": "_data_filter", "label": "Data Filter" },
   { "name": "_log_level", "label": "Log Level", "query": "ERROR,WARNING,INFO,SUCCESS" },
   { "name": "_status_keys", "label": "Workers", "query": "KEYS *" }
  ]
 },
 "panels": [
  {
   "title": "Queue Messages",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "columns": [
      { "selector": "name", "text": "1-StreamName", "type": "string" },
      { "selector": "state.messages", "text": "2-Messages", "type": "number" },
      { "selector": "state.consumer_count", "text": "3-Consumers", "type": "number" }
     ],
     "computed_columns": [
      { "selector": "", "text": "Name", "type": "string" }
     ],
     "json_options": {
      "root_is_not_array": false
     },
     "parser": "backend",
     "root_selector": "$.account_details[0].stream_detail[*]",
     "source": "url",
     "type": "json",
     "url": "/jsz?streams=true",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Recon Worker Logs",
   "type": "logs",
   "gridPos": { "h": 11, "w": 18, "x": 6, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=~\".*h3xrecon[_-]recon.*\"} !~ `^$` |= `$_recon_filter` |~ `(?P<loglevel>$_log_level)`"
    }
   ]
  },
  {
   "title": "New Assets",
   "type": "logs",
   "gridPos": { "h": 25, "w": 6, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{service_name=~\".*h3xrecon[_-]data.*\"} |~ `(?P<inserted>INSERTED)`"
    }
   ]
  },
  {
   "title": "Parsing Worker Logs",
   "type": "logs",
   "gridPos": { "h": 11, "w": 18, "x": 6, "y": 11 },
   "targets": [
    {
     "expr": "{service_name=~\".*h3xrecon[_-]parsing.*\"} !~ `^$` |= `$_parsing_filter` |~ `(?P<loglevel>$_log_level)`"
    }
   ]
  },
  {
   "title": "Data Worker Logs",
   "type": "logs",
   "gridPos": { "h": 11, "w": 18, "x": 6, "y": 22 },
   "targets": [
    {
     "expr": "{service_name=~\".*h3xrecon[_-]data.*\"} !~ `^$` |= `$_data_filter` |~ `(?P<loglevel>$_log_level)`"
    }
   ]
  }
 ]
}