FROM python:3.9-slim

WORKDIR /app

# Install additional system dependencies
RUN apt-get update && apt-get install -y \
    dnsutils \
    && rm -rf /var/lib/apt/lists/*

COPY docker/base/requirements.base.txt /app/requirements.txt

COPY h3xrecon /app/h3xrecon

ENV PYTHONPATH="/app"

RUN pip install \
        --upgrade \
        --no-cache-dir \
        -r requirements.txt