- name: Build and push to local registry
  community.docker.docker_image_build:
    path: "{{ image['path'] }}"
    dockerfile: "{{ image['dockerfile'] }}"
    platform: "{{ image['arch'] }}"
    name: "{{ image['name'] }}"
    rebuild: always
    outputs:
      - push: true
        type: image
  when: 
    - inventory_hostname == groups['processor'][0]
  delegate_to: "{{ groups['processor'][0] }}"
  loop:
  # BaseImage
  - path: "{{ h3xrecon_target_directory }}/BaseImage/"
    name: 127.0.0.1:5000/base:latest
    dockerfile: Dockerfile
    arch:
     - linux/amd64

  # Worker
  - path: "{{ h3xrecon_target_directory }}/Worker/"
    name: 127.0.0.1:5000/worker:latest
    dockerfile: Dockerfile
    arch:
     - linux/arm64
    
  # DataProcessor
  - path: "{{ h3xrecon_target_directory }}/Processor/"
    name: 127.0.0.1:5000/data_processor:latest
    dockerfile: Dockerfile.data_processor
    arch:
      - linux/amd64
  
  # JobProcessor
  - path: "{{ h3xrecon_target_directory }}/Processor/"
    name: 127.0.0.1:5000/job_processor:latest
    dockerfile: Dockerfile.job_processor
    arch:
      - linux/amd64

  # Logger
  - path: "{{ h3xrecon_target_directory }}/Processor/"
    name: 127.0.0.1:5000/logger:latest
    dockerfile: Dockerfile.logger
    arch:
      - linux/amd64
  
  # NATS
  - path: "{{ h3xrecon_target_directory }}/Processor/nats"
    name: 127.0.0.1:5000/nats:latest
    dockerfile: Dockerfile
    arch:
      - linux/amd64
  
  # PostgreSQL
  - path: "{{ h3xrecon_target_directory }}/Processor/pgsql"
    name: 127.0.0.1:5000/pgsql:latest
    dockerfile: Dockerfile
    arch:
      - linux/amd64
  
  loop_control:
    loop_var: image
