- name: Install Docker and Docker Compose Python libraries
  ansible.builtin.pip:
    name: 
      - docker
      - docker-compose
    state: present
    break_system_packages: true

- name: Add Docker official GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    filename: docker
    state: present

- name: Install Docker packages
  ansible.builtin.apt:
    pkg:
      - docker.io
    state: present
    update_cache: yes

- name: Install Loki plugin for Docker
  ansible.builtin.shell: docker plugin install grafana/loki-docker-driver:latest --alias loki --grant-all-permissions || true

- name: Set Docker logging driver
  ansible.builtin.copy:
    content: |
      {
        "log-driver": "loki",
        "log-opts": {
          "loki-url": "http://loki:3100/loki/api/v1/push"
        }
      }
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: '0644'
    

- name: Ensure Docker service is running
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: yes