- name: Logout from Tailscale network
  ansible.builtin.command: tailscale logout
  changed_when: false
  ignore_errors: true

- name: Stop Tailscale service
  ansible.builtin.systemd:
    name: tailscaled
    state: stopped
    enabled: no
  ignore_errors: true

- name: Remove Tailscale package
  ansible.builtin.apt:
    name: tailscale
    state: absent
    purge: yes

- name: Remove Tailscale repository
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/tailscale.list
    state: absent

- name: Remove Tailscale GPG key
  ansible.builtin.apt_key:
    id: 458CA832957F5868
    state: absent
  ignore_errors: true

- name: Remove Tailscale configuration and data
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /var/lib/tailscale
    - /var/run/tailscale
    - /etc/tailscale
  ignore_errors: true

- name: Remove Tailscale network interface
  ansible.builtin.command: ip link delete tailscale0
  ignore_errors: true
  changed_when: false
