- name: Leave Docker Swarm
  block:
    - name: Remove worker nodes from Swarm
      community.docker.docker_swarm:
        state: absent
        force: yes
      when: inventory_hostname not in groups['processor']
    
    - name: Force leave "orphaned" Docker Swarm
      ansible.builtin.command: docker swarm leave --force
      when: inventory_hostname not in groups['processor'][0]
      failed_when: false
      ignore_errors: true
    
    - name: Remove manager node from Swarm
      community.docker.docker_swarm:
        state: absent
        force: yes
      when: inventory_hostname == groups['processor'][0]

- name: Clean up Docker Swarm configuration
  block:
    - name: Remove Swarm-related files
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/docker/swarm
        - /var/lib/docker/swarm
        - /var/run/docker/swarm
      ignore_errors: true

- name: Reset Docker to non-Swarm state
  ansible.builtin.systemd:
    name: docker
    state: restarted