- name: Add Tailscale repository key
  ansible.builtin.apt_key:
    url: https://pkgs.tailscale.com/stable/ubuntu/noble.noarmor.gpg
    state: present

- name: Add Tailscale repository
  ansible.builtin.apt_repository:
    repo: deb https://pkgs.tailscale.com/stable/ubuntu noble main
    filename: tailscale
    state: present

- name: Install Tailscale package
  ansible.builtin.apt:
    name: tailscale
    state: present
    update_cache: yes

- name: Ensure tailscaled service is running
  ansible.builtin.systemd:
    name: tailscaled
    state: started
    enabled: yes

- name: Authenticate and enable Tailscale
  ansible.builtin.command: >
    tailscale up 
    --authkey="{{ lookup('env', 'TAILSCALE_AUTH_KEY') }}"
    --advertise-routes="{{ tailscale_subnet_routes }}" 
    --accept-routes=true --reset
  no_log: false
  register: tailscale_result
  changed_when: false