- name: Start h3xrecon stack
  hosts: processor
  vars_files:
    - vaults/vault.yaml
  tasks:
    - name: Create target directory
      ansible.builtin.file:
        path: "{{ h3xrecon_target_directory }}"
        state: directory

    - name: Copy compose files
      ansible.builtin.copy:
        src: "{{ file['src'] }}"
        dest: "{{ file['dest'] }}"
      loop:
        - src: ../docker/grafana
          dest: "{{ h3xrecon_target_directory }}/"
        - src: ../docker-compose.swarm.yaml
          dest: "{{ h3xrecon_target_directory }}/docker-compose.yaml"
      loop_control:
        loop_var: file
    - name: Install jsondiff python library
      ansible.builtin.pip:
        name: jsondiff
        state: present
    - name: Deploy Docker stack
      ansible.builtin.shell:
        chdir: "{{ h3xrecon_target_directory }}"
        cmd: docker stack deploy -c docker-compose.yaml h3xrecon
      environment:
        H3XRECON_DB_USER: h3xrecon
        H3XRECON_DB_NAME: h3xrecon
        H3XRECON_DB_HOST: database
        H3XRECON_DB_PASS: h3xrecon
        H3XRECON_REDIS_HOST: cache
        H3XRECON_REDIS_PORT: 6379
        H3XRECON_NATS_HOST: msgbroker
        H3XRECON_NATS_PORT: 4222
        H3XRECON_LOG_LEVEL: DEBUG
        H3XRECON_LOG_FILE_PATH: /app/logs/h3xrecon.log