---
- hosts: all
  become: yes
  gather_facts: false
  
  tasks:
    - name: Remove all Docker Swarm services
      ansible.builtin.include_tasks: tasks/remove_swarm_services.yaml

    - name: Leave Swarm cluster
      ansible.builtin.include_tasks: tasks/leave_swarm.yaml

    - name: Remove Tailscale
      ansible.builtin.include_tasks: tasks/remove_tailscale.yaml

    - name: Clean system
      block:
        - name: Update package cache after repository removal
          ansible.builtin.apt:
            update_cache: yes
          ignore_errors: true

        - name: Remove leftover dependencies
          ansible.builtin.apt:
            autoremove: yes
          ignore_errors: true

    - name: Verify removal
      block:
        - name: Check Docker Swarm status
          ansible.builtin.command: docker info
          register: docker_info
          changed_when: false
          failed_when: false

        - name: Display Docker info
          ansible.builtin.debug:
            var: docker_info.stdout_lines

        - name: Check Tailscale status
          ansible.builtin.command: which tailscale
          register: tailscale_check
          changed_when: false
          failed_when: false

        - name: Display Tailscale removal status
          ansible.builtin.debug:
            msg: "Tailscale {{ 'is completely removed' if tailscale_check.rc != 0 else 'might still have some components installed' }}"