- name: Setup Nodes for h3xrecon
  hosts: all
  become: true
  gather_facts: false
  
  vars_files:
  - vaults/tailscale_vault.yaml
  vars:
    tailscale_subnet_routes: "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
    docker_swarm_interface: "tailscale0"

  tasks:
    - {"name": "Test communication with all nodes", "ansible.builtin.include_tasks": "tasks/test_all_nodes.yaml"}
    - name: Install Tailscale
      ansible.builtin.include_tasks: tasks/install_tailscale.yaml
      when: lookup('ansible.builtin.env', 'H3XRECON_SWARM_MODE', default='lan') == 'tailscale'
    - {"name": "Install Docker", "ansible.builtin.include_tasks": "tasks/install_docker.yaml"}
    - {"name": "Configure Docker Swarm", "ansible.builtin.include_tasks": "tasks/configure_docker_swarm.yaml"}
    #- {"name": "Setup Dashboard", "ansible.builtin.include_tasks": "tasks/setup_dashboard.yaml"}
  
  handlers:
    - name: Restart Docker
      ansible.builtin.systemd:
        name: docker
        state: restarted

  post_tasks:
    - name: Verify Swarm cluster
      community.docker.docker_swarm_info:
      register: swarm_status
      delegate_to: "{{ groups['processor'][0] }}"
      run_once: true

    - name: Display Swarm cluster info
      ansible.builtin.debug:
        var: swarm_status
      delegate_to: "{{ groups['processor'][0] }}"
      run_once: true