FROM python:3.9-slim

WORKDIR /app

# Install additional system dependencies
RUN apt-get update && apt-get install -y \
    dnsutils \
    && rm -rf /var/lib/apt/lists/*

ENV PATH="$PATH:/root/go/bin:/root/.pdtm/go/bin:/usr/lib/go-1.15/bin"

RUN apt-get update && apt-get install -y \
    git \
    unzip \
    wget \
    && rm -rf /var/lib/apt/lists/*

COPY h3xrecon-cli /app/h3xrecon-cli

COPY h3xrecon-core /app/h3xrecon-core
    
RUN python3 -m venv /app/venv && \
    /app/venv/bin/pip install /app/h3xrecon-cli && \
    /app/venv/bin/pip install /app/h3xrecon-core

ENTRYPOINT ["/app/venv/bin/python3", "-m", "h3xrecon_cli.main"]

CMD ["-h"]