- name: Start h3xrecon stack
  hosts: processor
  vars_files:
    - vaults/vault.yaml
  tasks:
    - name: Deploy Docker stack
      delegate_to: localhost
      community.docker.docker_stack:
        state: present
        name: h3xrecon
        compose:
          - ../docker/docker-compose.yaml
      environment:
        DOCKER_HOST: ssh://{{ ansible_host }}