name: Release Chain

on:
  workflow_dispatch:

permissions:
  packages: write
  contents: write

jobs:
  build-core:
    uses: h3xitsec/h3xrecon-core/.github/workflows/build_and_release.yaml@develop
    secrets: inherit

  build-plugins:
    needs: build-core
    uses: h3xitsec/h3xrecon-plugins/.github/workflows/build_and_release.yaml@develop
    secrets: inherit

  build-server:
    needs: build-plugins
    uses: h3xitsec/h3xrecon-server/.github/workflows/build_and_release.yaml@develop
    secrets: inherit

  build-worker:
    needs: build-server
    uses: h3xitsec/h3xrecon-worker/.github/workflows/build_and_release.yaml@develop
    secrets: inherit

  build-main:
    needs: [build-core, build-plugins, build-server, build-worker]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Build and push database image
        uses: docker/build-push-action@v4
        with:
          context: ./docker/pgsql
          file: ./docker/pgsql/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/h3xrecon_pgsql:v0.0.1
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64