name: Build and Push Docker Images

on:
  # push:
  #   branches:
  #     - master
  workflow_dispatch:
permissions:
  packages: write
  contents: read
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push base image
        uses: docker/build-push-action@v4
        with:
          context: ./src
          file: ./src/docker/base/Dockerfile.base
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/h3xrecon_base:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64

      - name: Build and push worker image
        uses: docker/build-push-action@v4
        with:
          context: ./src
          file: ./src/docker/worker/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/h3xrecon_worker:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64

      - name: Build and push data processor image
        uses: docker/build-push-action@v4
        with:
          context: ./src
          file: ./src/docker/dataprocessor/Dockerfile.dataprocessor
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/h3xrecon_dataprocessor:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64

      - name: Build and push job processor image
        uses: docker/build-push-action@v4
        with:
          context: ./src
          file: ./src/docker/jobprocessor/Dockerfile.jobprocessor
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/h3xrecon_jobprocessor:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64

      # - name: Build and push logger image
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: ./src
      #     file: ./src/docker/logger/Dockerfile
      #     push: true
      #     tags: ghcr.io/${{ github.repository_owner }}/h3xrecon_logger:latest
      #     cache-from: type=gha
      #     cache-to: type=gha,mode=max
      #     platforms: linux/amd64
      
      - name: Build and push nats image
        uses: docker/build-push-action@v4
        with:
          context: ./src
          file: ./src/docker/nats/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/h3xrecon_nats:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64
      
      - name: Build and push pgsql image
        uses: docker/build-push-action@v4
        with:
          context: ./src
          file: ./src/docker/pgsql/Dockerfile.pgsql
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/h3xrecon_pgsql:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64