name: Release Chain

on:
  workflow_dispatch:

permissions:
  packages: write
  contents: write

jobs:
  build-core:
    uses: h3xitsec/h3xrecon-core/.github/workflows/build_and_release.yaml@develop
    secrets: inherit

  build-plugins:
    needs: build-core
    uses: h3xitsec/h3xrecon-plugins/.github/workflows/build_and_release.yaml@develop
    secrets: inherit

  build-server:
    needs: [build-plugins, build-core]
    uses: h3xitsec/h3xrecon-server/.github/workflows/build_and_release.yaml@develop
    secrets: inherit

  build-worker:
    needs: [build-server, build-core, build-plugins]
    uses: h3xitsec/h3xrecon-worker/.github/workflows/build_and_release.yaml@develop
    secrets: inherit

  build-database:
    uses: h3xitsec/h3xrecon/.github/workflows/build-push.yaml@develop
    secrets: inherit