name: Build and Push Docker Images

on:
  # push:
  #   branches:
  #     - master
  workflow_dispatch:
permissions:
  packages: write
  contents: read
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push h3xrecon-server image
        uses: docker/build-push-action@v4
        with:
          context: ./docker/server
          file: ./docker/server/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/h3xrecon_server:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64
      
      - name: Build and push h3xrecon-worker image
        uses: docker/build-push-action@v4
        with:
          context: ./docker/worker
          file: ./docker/worker/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/h3xrecon_worker:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64
      
      - name: Build and push h3xrecon-client image
        uses: docker/build-push-action@v4
        with:
          context: ./docker/cli
          file: ./docker/cli/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/h3xrecon_client:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64
      
      - name: Build and push database image
        uses: docker/build-push-action@v4
        with:
          context: ./docker/pgsql
          file: ./docker/pgsql/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/h3xrecon_pgsql:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64
      
      - name: Build and push msgbroker image
        uses: docker/build-push-action@v4
        with:
          context: ./docker/msgbroker
          file: ./docker/msgbroker/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/h3xrecon_msgbroker:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64